#Addresses
GET {{URL}}/addresses
Content-Type: application/json

GET {{URL}}/addresses/1
Content-Type: application/json

#Vaccines
GET {{URL}}/vaccines
Content-Type: application/json

GET {{URL}}/vaccines/1
Content-Type: application/json

#Patients
GET {{URL}}/patients
Content-Type: patients/json

GET {{URL}}/patients/1
Content-Type: application/json

#Nurses
GET {{URL}}/nurses
Content-Type: application/json

GET {{URL}}/nurses/1
Content-Type: application/json

#Establishments
GET {{URL}}/establishments
Content-Type: application/json

GET {{URL}}/establishments/1
Content-Type: application/json

#Vaccine certificates
GET {{URL}}/vaccine_certificates
Content-Type: application/json

GET {{URL}}/vaccine_certificates/1
Content-Type: application/json

#Administrators
GET {{URL}}/administrators
Content-Type: application/json

GET {{URL}}/administrators/1
Content-Type: application/json
