#Addresses
DELETE {{URL}}/addresses
Content-Type: application/json

DELETE {{URL}}/addresses/1
Content-Type: application/json

#Vaccines
DELETE {{URL}}/vaccines
Content-Type: application/json

DELETE {{URL}}/vaccines/1
Content-Type: application/json

#Patients
DELETE {{URL}}/patients
Content-Type: patients/json

DELETE {{URL}}/patients/1
Content-Type: application/json

#Nurses
DELETE {{URL}}/nurses
Content-Type: application/json

DELETE {{URL}}/nurses/1
Content-Type: application/json

#Establishments
DELETE {{URL}}/establishments
Content-Type: application/json

DELETE {{URL}}/establishments/1
Content-Type: application/json

#Vaccine certificates
DELETE {{URL}}/vaccine_certificates
Content-Type: application/json

DELETE {{URL}}/vaccine_certificates/1
Content-Type: application/json

#Administrators
DELETE {{URL}}/administrators
Content-Type: application/json

DELETE {{URL}}/administrators/1
Content-Type: application/json
