POST {{URL}}/patients
Content-Type: application/json

{
    "first_name": "Bryan",
    "last_name": "Baron",
    "identification_number": "1056622322",
    "identification_expedition_date": "2020-07-23",
    "phone_number": "38827736728",
    "email_address": "Bryan.baron55@gmail.com",
}
