#Address
PUT {{URL}}/addresses
Content-Type: application/json

{
    "city": "Medellin",
    "neighborhood_name": "Comuna 13",
    "street_name": "hueco",
    "street_number": 23,
    "cardinal_location": "Sur",
    "patients": 1,
    "establishments": null
}

#Vaccines
PUT {{URL}}/vaccines

{
    "name": "Moderna",
    "manufacter_date": "2022-02-16",
    "expiration_date": "2022-05-16",
    "vaccine_certificates": []
}

#Patients
PUT {{URL}}/patients
Content-Type: application/json

{
    "first_name": "Sandra",
    "last_name": "Murcia",
    "identification_number": "923482349",
    "identification_expedition_date": "2020-07-23",
    "phone_number": "92348239",
    "email_address": "Sandra.murcia97@gmail.com",
    "addresses": [],
    "vaccine_certificate": null
}

#Nurses
PUT {{URL}}/nurses
Content-Type: application/json

{
    "first_name": "Tatiana",
    "last_name": "Murcia",
    "identification_number": "2392839234",
    "identification_expedition_date": "2020-05-22",
    "phone_number": "4427736728",
    "email_address": "murciat35@gmail.com",
    "nurse_rol": "Jefe",
    "vaccine_certificates": null
}

#Establishments
PUT {{URL}}/establishments
Content-Type: application/json

{
    "name": "EPS Sanitas",
    "address_id": 1,
    "contact_number": "239403829048",
    "contact_email_address": "sanitas@test.com",
    "vaccine_certificates": null
}

#Vaccine certificates
PUT {{URL}}/vaccine_certificates
Content-Type: application/json

{
    "vaccine_id": 2,
    "patient_id": 2,
    "nurse_id": 2,
    "establishment_id": 2,
    "vaccine_application_date": "2022-12-13",
    "next_vaccine_application_date": "2023-03-13"
}

#Administrators
PUT {{URL}}/administrators
Content-Type: application/json

{
    "first_name": "MrFixThis",
    "last_name": "admin",
    "identification_number": "923849023",
    "identification_expedition_date": "2020-07-23",
    "phone_number": "92390832",
    "email_address": "admin@test.com",
}
